MySQL:
  host: "localhost"
  port: 3306
  database: "eft"
  username: "root"
  password: "password"

inventory:
  hideout-menu:
    title: "&eHideout Menu"
    upgrades:
      title: "&eHideout Upgrades &7(Right-Click)"
      lore:
        - ""
        - "&7Right-click this menu to be able"
        - "&7to upgrade certain areas of your"
        - "&7hideout."
    arenas:
      title: "&eJoin an Arena &7(Right-Click)"
      lore:
        - ""
        - "&7Right-click this menu to join"
        - "&7the queue for an arena."
  upgrades-menu:
    title: "&eStation Upgrades"
    station:
      lore-locked:
        - ""
        - "&7Right-click this item to unlock"
        - "&7the &e%name% &7in your Hideout."
        - ""
        - "&7This upgrade costs: &e%amount% COINS"
        - "&7You currently have: &e%has%"
      lore-unlocked:
        - ""
        - "&7You have already unlocked this"
        - "&7portion of your Hideout."

stations:
  prices:
    EXTRA_CHESTS: 1000
    INTELLIGENCE: 1250
    WORKBENCH: 1300
    FARM: 1350
    SHOOTING_RANGE: 1400
  maxed-out: "&cThis station is already maxed out and can't be further upgraded!"
  not-enough-coins: "&cYou don't have enough coins to upgrade this station!"
